name: Tetris Game Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame

    - name: Run Tetris game
      run: |
        python tetris_game.py

    - name: Run tests
      run: |
        python -m unittest discover -s tests

    - name: Display test results
      run: |
        cat test-results.txt
